name: Build and Deploy Package

on:
  push:
    branches:
      - main

jobs: 
    build-and-deploy:
        runs-on: ubuntu-latest        
        steps:
            - uses: actions/checkout@main              
            - name: Setup .Net Core
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: '8.0.x'
                
            - name: Build with Dotnet
              run: dotnet build --configuration release
              
            - name: Testando Aplicacao
              run: dotnet test
            
            - name: Create the Package v1
              run: dotnet pack --configuration release
              
            - name: Publish
              run: dotnet nuget push "MoneyExtension2/bin/Release/*.nupkg --api-key ${{secrets.NUGET_TOKEN}} --source https://api.nuget.org/v3/index.json"
              # --api-key oy2kvsutk3erww3xoaeqncb5qufuwfbu5iy3hbzf35sxii --source https://api.nuget.org/v3/index.json